server:
  port: 8082

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/ecom_products?authSource=admin}

    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      password: ${SPRING_REDIS_PASSWORD:redis123}
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 min cache TTL

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:admin123@localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30